# This is a basic workflow to help you get started with Actions

name: Windows 2022 RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Test background
        uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
          ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
          password: "Aa123456"
          foreground: true
